### ISSUE TITLE
Question about decoder

### ISSUE THREAD

**Issue by shihanmax** [sakuranew/PointerNet-pytorch#2]
Hi! thanks for your work!

I  (possibly) found a bug in Decoder at line 114 of your code:

```Python
cur_score=self.att(state,encoder_output,mask)
indice=cur_score.argmax(1)
indice=indice.view(-1,1,1).expand(-1,-1,d_input)
```

considering that `argmax` function can't retain the computing graph, I'm wondering if this can work as expected?

**Comment by shihanmax** [comment]
Sorry it was my fault, since the `indice` is just used to select which encoder timestamp to use, it's totally OK to use argmax here...

**Comment by sakuranew** [comment]
yes，you are right,indice&nbsp;Don't need to compute grident



---Original---
